subtr <- read.table("./train/subject_train.txt")
subt <- read.table("./test/subject_test.txt")
trset <- read.table("./train/X_train.txt")
trlabs <- read.table("./train/Y_train.txt")
features <- read.table("features.txt")
alabs <- read.table("activity_labels.txt")
tset <- read.table("./test/X_test.txt")
tlabs <- read.table("./test/Y_test.txt")
tcomb <- cbind(tset, subt, tlabs)
trcomb <- cbind(trset, subtr, trlabs)
comb <- rbind(tcomb, trcomb)
dummy <- data.frame(562:563, rbind("Subject", "ActivityNum"))
names(dummy) <- c("V1", "V2")
fhead <- rbind(features, dummy)
names(comb) <- fhead[,2]
temp <- comb[!duplicated(names(comb))]
cleancomb <- select(temp, contains("mean()"), contains("std()"), matches("Subject"), matches("ActivityNum"))
names(alabs) <- c("V1", "ActivityDesc")
combfinal <- merge(cleancomb, alabs, by.x = "ActivityNum", by.y = "V1")
summarizeddata <- ddply(combfinal, .(Subject, ActivityDesc), numcolwise(mean))
write.table(summarizeddata, file = "./Step5Submission.txt", row.names = FALSE)